"""
agents.py - LLM Agent Functions
================================

This file contains every function that calls an LLM:

  1. validate_user_input()                    - Pure Pydantic validation (no LLM).
  2. create_customer_query()                  - Uses Pydantic AI + Gemini to
                                                enrich a UserInput into a
                                                CustomerQuery.
  3. decide_next_action_with_tools()          - Uses OpenAI (GPT-4o) with
                                                function/tool calling to decide
                                                what action to take.
  4. get_tool_outputs()                       - Executes the tools the LLM
                                                requested.
  5. generate_structured_support_ticket()     - Uses Anthropic (Claude) via the
                                                Instructor library to produce a
                                                fully validated SupportTicket.

Together these functions form a multi-step pipeline:

  Raw JSON ──► UserInput ──► CustomerQuery ──► Tool Calls ──► SupportTicket
"""

import json
from datetime import datetime

from openai import OpenAI
import anthropic
import instructor
from pydantic_ai import Agent

from models import (
    UserInput,
    CustomerQuery,
    SupportTicket,
    FAQLookupArgs,
    CheckOrderStatusArgs,
)
from tools import (
    lookup_faq_answer,
    check_order_status,
    tool_definitions,
)


# ---------------------------------------------------------------------------
# 1. Validate raw user input
# ---------------------------------------------------------------------------
def validate_user_input(user_json: str) -> UserInput | None:
    """Parse and validate a JSON string into a UserInput model.

    Returns a UserInput instance on success, or None if validation fails.
    Pydantic automatically checks types, required fields, and custom
    validators (like the order_id format).
    """
    try:
        user_input = UserInput.model_validate_json(user_json)
        print("✓ User input validated successfully.")
        return user_input
    except Exception as e:
        print(f"✗ Validation error: {e}")
        return None


# ---------------------------------------------------------------------------
# 2. Enrich user input into a CustomerQuery using Pydantic AI + Gemini
# ---------------------------------------------------------------------------
async def create_customer_query(valid_user_json: str) -> CustomerQuery:
    """Send the validated user JSON to Gemini via Pydantic AI.

    The LLM reads the user's query and infers additional fields like
    priority, category, is_complaint, and tags.  Pydantic AI ensures
    the LLM's response conforms to the CustomerQuery schema.
    """
    customer_query_agent = Agent(
        model="google-gla:gemini-2.5-flash",
        output_type=CustomerQuery,
    )
    response = await customer_query_agent.run(valid_user_json)
    print("✓ CustomerQuery generated by Gemini.")
    return response.output


# ---------------------------------------------------------------------------
# 3. Ask OpenAI which tools to call (function calling)
# ---------------------------------------------------------------------------

# Initialize the OpenAI client (reads OPENAI_API_KEY from environment)
openai_client = OpenAI()


def decide_next_action_with_tools(customer_query: CustomerQuery):
    """Send the CustomerQuery to GPT-4o along with available tool definitions.

    The LLM decides whether it needs to call any tools (e.g. look up an FAQ
    or check an order status) before it can resolve the customer's issue.

    Returns:
        message    - The LLM's response message object.
        tool_calls - A list of tool-call objects the LLM wants to execute
                     (may be None if no tools are needed).
        messages   - The full conversation history (needed for follow-up calls).
    """
    # Build a system prompt that includes the SupportTicket schema so the LLM
    # understands what information it ultimately needs to gather.
    support_ticket_schema = json.dumps(SupportTicket.model_json_schema(), indent=2)
    system_prompt = f"""
        You are a helpful customer support agent. Your job is to determine
        what support action should be taken for the customer, based on the
        customer query and the expected fields in the SupportTicket schema
        below. If more information on a particular order_id or FAQ response
        would be helpful in responding to the user query, call the appropriate
        tool. If an order_id is present in the query, always look up the
        order status.

        SupportTicket JSON schema:
        {support_ticket_schema}
    """

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": str(customer_query.model_dump())},
    ]

    response = openai_client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        tools=tool_definitions,
        tool_choice="auto",
    )

    message = response.choices[0].message
    tool_calls = getattr(message, "tool_calls", None)
    return message, tool_calls, messages


# ---------------------------------------------------------------------------
# 4. Execute the tools that the LLM requested
# ---------------------------------------------------------------------------
def get_tool_outputs(tool_calls) -> list:
    """Loop through each tool call from the LLM and execute the
    corresponding local function.

    Each tool call contains:
      - function.name      → which tool to run
      - function.arguments → JSON string of arguments

    We parse the arguments into the matching Pydantic model, call the
    function, and collect results.
    """
    tool_outputs = []

    if not tool_calls:
        print("  (No tool calls requested by the LLM.)")
        return tool_outputs

    for tool_call in tool_calls:
        func_name = tool_call.function.name

        if func_name == "lookup_faq_answer":
            print(f"  → Calling lookup_faq_answer ...")
            args = FAQLookupArgs.model_validate_json(tool_call.function.arguments)
            result = lookup_faq_answer(args)
            tool_outputs.append({"tool_call_id": tool_call.id, "output": result})
            print(f"    Result: {result}")

        elif func_name == "check_order_status":
            print(f"  → Calling check_order_status ...")
            args = CheckOrderStatusArgs.model_validate_json(
                tool_call.function.arguments
            )
            result = check_order_status(args)
            tool_outputs.append({"tool_call_id": tool_call.id, "output": result})
            print(f"    Result: {result}")

        else:
            print(f"  ⚠ Unknown tool requested: {func_name}")

    return tool_outputs


# ---------------------------------------------------------------------------
# 5. Generate the final SupportTicket using Anthropic (Claude) + Instructor
# ---------------------------------------------------------------------------

# Instructor wraps the Anthropic client so the LLM response is automatically
# parsed into a Pydantic model.
anthropic_client = instructor.from_anthropic(anthropic.Anthropic())


def generate_structured_support_ticket(
    customer_query: CustomerQuery,
    message,
    tool_outputs: list,
) -> SupportTicket:
    """Combine all gathered information and ask Claude to produce a
    fully structured SupportTicket.

    Inputs:
        customer_query - The enriched customer query.
        message        - The OpenAI LLM's response (may contain reasoning).
        tool_outputs   - Results from any tools that were executed.

    Returns:
        A validated SupportTicket Pydantic model instance.
    """
    # Format tool results into a readable string for the prompt
    if tool_outputs:
        tool_results_str = "\n".join(
            f"Tool: {out['tool_call_id']}  Output: {json.dumps(out['output'])}"
            for out in tool_outputs
        )
    else:
        tool_results_str = "No tool calls were made."

    prompt = f"""
        You are a support agent. Use all information below to generate
        a support ticket as a validated Pydantic model.

        Customer query:
        {customer_query.model_dump_json(indent=2)}

        LLM message:
        {str(message.content)}

        Tool results:
        {tool_results_str}
    """

    # Instructor ensures the response matches the SupportTicket schema
    support_ticket: SupportTicket = anthropic_client.messages.create(
        model="claude-3-7-sonnet-latest",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
        response_model=SupportTicket,
    )

    # Stamp the creation date ourselves (the LLM doesn't know the real time)
    support_ticket.creation_date = datetime.now()
    return support_ticket
